/*
 * Copyright  1990-2009 Sun Microsystems, Inc. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 only, as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License version 2 for more details (a copy is
 * included at /legal/license.txt).
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 * 
 * Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
 * Clara, CA 95054 or visit www.sun.com if you need additional
 * information or have any questions.
 */


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_kvem_Sublime */

#ifndef _Included_com_sun_kvem_Sublime
#define _Included_com_sun_kvem_Sublime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_kvem_Sublime
 * Method:    returnResult
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_sun_kvem_Sublime_returnResult
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_sun_kvem_Sublime
 * Method:    process
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_kvem_Sublime_process
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_kvem_Sublime
 * Method:    getSublimeProcessId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_kvem_Sublime_getSublimeProcessId
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_kvem_Sublime
 * Method:    setSublimeProcessId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sun_kvem_Sublime_setSublimeProcessId
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sun_kvem_Sublime
 * Method:    setTempFilesDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_kvem_Sublime_setTempFilesDirectory
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
