#!/bin/sh
#
# Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved. 
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 only,
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# version 2 for more details (a copy is included at /legal/license.txt).
# 
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
# 
# Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa Clara,
# CA 95054 or visit www.sun.com if you need additional information or have
# any questions.
#
#
# How to use:
#   makecdcams <buildflavor> <buildtype> <PRESENTATION_MODES=xxx> <clean>
#     buildflavors can be linux-x86-suse, linux-arm-zaurus, etc.
#     buildtype can be personal, basis, appmanager, appmanager_basis
#
# Example of commands:
#   makecdcams - (defaults to linux-x86-suse, appmanager build)
#   makecdcams linux-arm-zaurus basis
#   makecdcams linux-x86-suse appmanager PRESENTATION_MODES=all
#   makecdcams linux-x86-suse appmanager PRESENTATION_MODES=AwtPDA
#
#     Use the target 'appmanager_create' to create a gzip tarfile, Ex.
#   makecdcams linux-x86-suse appmanager PRESENTATION_MODES=AwtPDA appmanager_create

##### Might want to modify these variables #####
if [ -z "$CDCAMS_HOME" ] ; then
    CDCAMS_HOME=/home/`whoami`/cdcams-master
    echo "CDCAMS_HOME not set.  Defaulting to $CDCAMS_HOME."
fi

#
# Set values needed to properly build the JSR-124 RI. J2EE_HOME
# must point to an installation of the J2EE 1.3 server, which
# can be retrieved from http://java.sun.com/j2ee/1.3/download.html.
# JSR124_HOME must point to an instance of the JSR-124 RI source
# tree, which can be retrieved from
# http://java.sun.com/j2ee/provisioning/download.html
[ -z "$J2EE_HOME" ] && J2EE_HOME=/net/maxfield/export/share/installs/j2sdkee1.3.1
JSR124_HOME=/net/maxfield/export/share/installs/j2ee_cp_ri_1_0
################################################

if [ -n "$1" ]; then
    BUILDFLAVOR=$1
    shift
fi
if [ -n "$1" ]; then
    BUILDTYPE=$1
    shift
fi

# default build flavor to linux-x86-suse if none specified
if [ "$BUILDFLAVOR" = "" ]; then
  BUILDFLAVOR="linux-x86-suse"
fi

# default build type to personal if none specified
if [ "$BUILDTYPE" = "" ]; then
  PLATFORM="J2ME_PLATFORM=appmanager"
elif [ "$BUILDTYPE" = "personal" ]; then
  PLATFORM="J2ME_CLASSLIB=personal"
elif [ "$BUILDTYPE" = "basis" ]; then
  PLATFORM="J2ME_CLASSLIB=basis"
elif [ "$BUILDTYPE" = "foundation" ]; then
  PLATFORM="J2ME_CLASSLIB=foundation"
elif [ "$BUILDTYPE" = "appmanager" ]; then
  PLATFORM="J2ME_PLATFORM=appmanager"
elif [ "$BUILDTYPE" = "appmanager_basis" ]; then
  PLATFORM="J2ME_PLATFORM=appmanager J2ME_CLASSLIB=basis"
else
  echo "Invalid BUILDTYPE value."
  exit 0
fi

unset QTDIR

HOSTPLATFORM=`uname -s`
if [ "$HOSTPLATFORM" = "Linux" ]; then
  MAKE=/usr/bin/make
fi

PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin

########## linux-x86-suse ################
if [ "$BUILDFLAVOR" = "linux-x86-suse" -o \
     $BUILDFLAVOR = "linux-x86-redhat" ]; then
  OPTIONS="JDK_VERSION=jdk1.4.2 $PLATFORM CVM_OPTIMIZED=true CVM_DEBUG=false CVM_TERSEOUTPUT=true CVM_PRELOAD_LIB=false CVM_TRACE=false J2EE_HOME=$J2EE_HOME JSR124_HOME=$JSR124_HOME"
########## linux-arm-zaurus ##############
elif [ "$BUILDFLAVOR" = "linux-arm-zaurus" ]; then
    OPTIONS="JDK_VERSION=jdk1.4.2 $PLATFORM CVM_JIT=true CVM_OPTIMIZED=true CVM_DEBUG=true CVM_TRACE=false CVM_PRELOAD_LIB=false CVM_TERSEOUTPUT=true"
########## linux-mips-cobalt ##############
elif [ "$BUILDFLAVOR" = "linux-mips-cobalt" ]; then
OPTIONS="JDK_VERSION=jdk1.4.2 $PLATFORM CVM_OPTIMIZED=true CVM_DEBUG=false CVM_TERSEOUTPUT=false CVM_PRELOAD_LIB=false "
else
########## platform unknown ##############
  echo "This platform is not supported. Exiting."
  exit 0
fi

COMMAND="cd $CDCAMS_HOME/build/$BUILDFLAVOR"
echo $COMMAND
$COMMAND

COMMAND="$MAKE $OPTIONS $*"
echo "$COMMAND"
$COMMAND

exit 0
